# Generated by Django 6.0.6 on 2026-08-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SongQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_id', models.CharField(max_length=50)),
                ('thumbnail', models.URLField(blank=True, max_length=500, null=True)),
                ('channel', models.CharField(blank=True, max_length=255, null=True)),
                ('requested_by', models.CharField(default='ลูกค้าในร้าน', max_length=100)),
                ('is_played', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
