# Generated by Django 6.0.6 on 2026-08-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songqueue',
            name='client_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
