# Generated by Django 6.0.6 on 2026-09-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_clientlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=50, unique=True)),
                ('plays', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
