# Generated by Django 6.0.6 on 2026-09-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_genre_tag_alter_playlist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='songqueue',
            name='artwork',
            field=models.ImageField(blank=True, null=True, upload_to='artwork/'),
        ),
    ]
