# Generated by Django 6.0.6 on 2026-10-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_playlistsong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, max_length=30, unique=True),
        ),
    ]
